export const GREETINGS = [
  'Un gusto verte de nuevo',
  '¡Un placer verte de nuevo!',
  '¡Qué bueno tenerte aquí otra vez!',
  '¡Bienvenido nuevamente!',
  '¡Saludos cordiales!',
  '¡Espero que estés bien.',
  '¡Un gusto verte otra vez!',
  '¡Espero que hayas tenido un buen día!',
  '¡Saludos afectuosos!',
  '¡Bienvenido de vuelta!',
  '¡Un saludo caluroso!',
  '¡Espero que estés teniendo un buen día!',
  '¡Un saludo y hasta luego!',
  '¡Espero que todo vaya bien!',
  '¡Saludos y bendiciones!',
  '¡Siempre es un gusto verte!',
  '¡Espero que estés de maravilla!',
  '¡Un placer verte otra vez!',
  '¡Saludos, siempre es bueno verte!',
  '¡Un saludo y que tengas un día fantástico!',
  '¡Espero que estés disfrutando tu día!',
  '¡Siempre es un gusto verte de nuevo!',
  '¡Que tengas un día maravilloso!',
  '¡Un gusto verte de nuevo por aquí!',
  '¡Espero que estés teniendo una excelente jornada!',
  '¡Saludos y espero que todo vaya bien!',
  '¡Espero que estés teniendo un buen día!',
  '¡Que tengas una gran experiencia!',
  '¡Un gusto saludarte de nuevo!',
  '¡Saludos y que tengas un buen día!',
  '¡Espero que estés disfrutando de tu tiempo aquí!',
  '¡Un saludo y que tengas éxito en todo!',
  '¡Espero que estés pasando un día increíble!',
  '¡Un gusto verte por estos lares!',
  '¡Que tengas un día lleno de alegría!',
  '¡Espero que estés teniendo una jornada maravillosa!',
  '¡Un saludo y hasta pronto!',
  '¡Espero que todo vaya genial!',
  '¡Saludos y espero que estés bien!',
  '¡Espero que estés pasando un buen día!',
  '¡Que tengas un día espectacular!',
  '¡Un gusto saludarte de nuevo!',
  '¡Espero que estés disfrutando de tu tiempo aquí!',
  '¡Un saludo y hasta luego!',
  '¡Que tengas un día lleno de éxitos!',
  '¡Espero que estés pasando un día estupendo!',
  '¡Un gusto verte por aquí nuevamente!',
  '¡Espero que estés teniendo una jornada fantástica!',
  '¡Saludos y que tengas un buen día!',
  '¡Espero que estés disfrutando tu estancia!',
  '¡Que tengas un día maravilloso y lleno de bendiciones!',
]
