export const MOTIVATIONAL_PHRASES = [
    '"Todo lo que necesitas es dentro de ti mismo" - Allan Rufus',
    '"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que estás haciendo, tendrás éxito" - Albert Schweitzer',
    '"No busques la felicidad, créala" - Autor desconocido',
    '"Cada día es una nueva oportunidad para ser feliz" - Autor desconocido',
    '"El fracaso es una oportunidad para empezar de nuevo con más experiencia" - Henry Ford',
    '"La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo" - George Bernard Shaw',
    '"Nunca eres demasiado viejo para tener otra meta o para soñar un nuevo sueño" - C.S. Lewis',
    '"La motivación te lleva a la acción, y la acción te lleva al éxito" - Autor desconocido',
    '"El éxito es la suma de pequeños esfuerzos repetidos día tras día" - Robert Collier',
    '"La vida es 10% lo que te sucede y 90% cómo reaccionas ante ello" - Charles R. Swindoll',
    '"Haz algo hoy que tu yo futuro te agradecerá por" - Sean Patrick Flanery',
    '"El cambio no es algo que esperar, es algo que crear" - Autor desconocido',
    '"Todo es posible si te atreves a creerlo" - Autor desconocido',
    '"Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud" - Maya Angelou',
    '"No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando no lo intentas" - Jack Canfield',
    '"Nada es imposible, la palabra misma dice <soy posible>" - Audrey Hepburn',
    '"La confianza en uno mismo es el primer secreto del éxito" - Ralph Waldo Emerson',
    '"El éxito es la mejor venganza para aquellos que te desean el mal" - Autor desconocido',
    '"La vida es un 10% lo que me pasa y 90% cómo reacciono a ello" - John C. Maxwell',
    '"No busques la aprobación de los demás, busca tu propia aprobación" - Autor desconocido',
    '"No puedes cambiar el viento, pero puedes ajustar tus velas" - Autor desconocido',
    '"No te rindas, las cosas buenas llevan tiempo" - Autor desconocido',
    '"Si quieres algo que nunca tuviste, tienes que hacer algo que nunca hiciste" - Autor desconocido',
    '"No permitas que tus miedos te detengan, permíteles que te motiven" - Autor desconocido',
    '"Si buscas resultados distintos, no hagas siempre lo mismo" - Albert Einstein',
    '"El éxito no es una estación a la que se llega, sino una manera de viajar" - Margaret Lee Runbeck',
    '"El fracaso es la oportunidad de empezar de nuevo, pero más inteligentemente" - Henry Ford',
    '"No importa lo lento que vayas, siempre y cuando no te detengas" - Confucio',
    '"La felicidad no es algo hecho. Viene de tus propias acciones" - Dalai',
    '"Empieza donde estás, usa lo que tienes, haz lo que puedes." - Arthur Ashe',
    '"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que estás haciendo, tendrás éxito." - Albert Schweitzer',
    '"No importa lo lentamente que vayas mientras no te detengas." - Confucio',
    '"Tú eres el único responsable de tu felicidad y éxito." - Paulo Coelho',
    '"El éxito no es para los que piensan en renunciar." - Autor desconocido',
    '"Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud." - Maya Angelou',
    '"Si no te gusta algo, déjalo ir. Si no te deja ir, aprende a amarlo." - Autor desconocido',
    '"No dejes que el miedo a perder sea mayor que la emoción de ganar." - Robert Kiyosaki',
    '"Si puedes soñarlo, puedes lograrlo." - Walt Disney',
    '"No te rindas, cada fracaso es una oportunidad para comenzar de nuevo con más experiencia." - Henry Ford',
]